name: Hello World

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Hello World
        run: echo "Hello World!"
    

  other: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Hello Other
        run: echo "Hello Other!"