name: Test

on:
  push:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with: 
          node-version: latest

      - name: Node Version
        run: node --version
    
